// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Picklr.Models;

#nullable disable

namespace Picklr.Migrations
{
    [DbContext(typeof(PicklrContext))]
    partial class PicklrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Picklr.Models.AppUser", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "alice@picklr.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Role = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "bob@picklr.com",
                            FirstName = "Bob",
                            LastName = "Jones",
                            Role = "Client"
                        });
                });

            modelBuilder.Entity("Picklr.Models.Club", b =>
                {
                    b.Property<int>("ClubID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClubID");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            ClubID = 1,
                            Description = "Our flagship downtown club with 10 indoor courts.",
                            Location = "123 Main St, Chicago, IL",
                            Name = "Picklr Downtown"
                        },
                        new
                        {
                            ClubID = 2,
                            Description = "A vibrant outdoor facility with 8 courts and a pro shop.",
                            Location = "456 Oak Ave, Evanston, IL",
                            Name = "Picklr Northside"
                        },
                        new
                        {
                            ClubID = 3,
                            Description = "An indoor pickleball club located in New York.",
                            Location = "789 Broadway, New York, NY",
                            Name = "Picklr New York"
                        });
                });

            modelBuilder.Entity("Picklr.Models.PicklProgram", b =>
                {
                    b.Property<int>("ProgramID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClubID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Fee")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Friday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monday")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Saturday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Sunday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Thursday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProgramID");

                    b.HasIndex("ClubID");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            ProgramID = 1,
                            ClubID = 1,
                            Description = "Drop-in open play for new players. No experience needed.",
                            Fee = 10.00m,
                            Friday = true,
                            Monday = true,
                            Name = "Beginner Open Play",
                            Saturday = false,
                            Sunday = false,
                            Thursday = false,
                            Tuesday = false,
                            Wednesday = true
                        },
                        new
                        {
                            ProgramID = 2,
                            ClubID = 1,
                            Description = "Weekly skill-building clinic led by a certified coach.",
                            Fee = 25.00m,
                            Friday = false,
                            Monday = false,
                            Name = "Intermediate Clinic",
                            Saturday = false,
                            Sunday = false,
                            Thursday = true,
                            Tuesday = true,
                            Wednesday = false
                        },
                        new
                        {
                            ProgramID = 3,
                            ClubID = 2,
                            Description = "Competitive round-robin tournament for rated players.",
                            Fee = 40.00m,
                            Friday = false,
                            Monday = false,
                            Name = "Advanced Tournament",
                            Saturday = true,
                            Sunday = true,
                            Thursday = false,
                            Tuesday = false,
                            Wednesday = false
                        },
                        new
                        {
                            ProgramID = 4,
                            ClubID = 3,
                            Description = "Introduction to pickleball for new players.",
                            Fee = 10.00m,
                            Friday = true,
                            Monday = true,
                            Name = "Picklr 101",
                            Saturday = true,
                            Sunday = true,
                            Thursday = true,
                            Tuesday = true,
                            Wednesday = true
                        },
                        new
                        {
                            ProgramID = 5,
                            ClubID = 2,
                            Description = "Weekend social play for all skill levels.",
                            Fee = 0.00m,
                            Friday = false,
                            Monday = false,
                            Name = "Picklr Social",
                            Saturday = true,
                            Sunday = false,
                            Thursday = false,
                            Tuesday = false,
                            Wednesday = false
                        });
                });

            modelBuilder.Entity("Picklr.Models.PicklProgram", b =>
                {
                    b.HasOne("Picklr.Models.Club", "Club")
                        .WithMany("Programs")
                        .HasForeignKey("ClubID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("Picklr.Models.Club", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
